DEVICE          : cuda                        # device used for evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/inference_nuove'     # output folder name
GPUs            : 1
GPU_IDs         : [0]

MODEL:
  NAME          : MMSFormer
  BACKBONE      : MMSFormer-B3
  PRETRAINED    : ''
  RESUME        : ''

DATASET:
  NAME          : MORTARS
  ROOT          : 'data/mortars'
  IGNORE_LABEL  : 3
  MODALS        : ['paralleli', 'incrociati']
  NUM_CLASSES   : 2

EVAL:
  MODEL_PATH    : 'output/MMSFormer/MMSF-EXP2-PHOTO-AUG/MMSFormer_MMSFormer-B3_MORTARS_epoch50_78.41.pth'
  IMAGE_SIZE    : [512, 512]
  BATCH_SIZE    : 1

TEST:
  MODEL_PATH    : 'output/MMSFormer/MMSF-EXP2-PHOTO-AUG/MMSFormer_MMSFormer-B3_MORTARS_epoch50_78.41.pth'
  IMAGE_SIZE    : [512, 512]
  VIS_SAVE_DIR  : 'output/inference_nuove_exp2/UNITO_B'
  FILE          : 'data/nuove_patches/UNITO_B'
  OVERLAY       : false
  INVERT_PALETTE: true # true per ottenere aggregati verdi e legante nero

